version: "2"
services:
  mysql:
    image: mysql/mysql-server:5.6
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_ROOT_HOST=%"
    ports:
      - 3306:3306
